#ifndef _UPPERCASE_H_
#define _UPPERCASE_H_

#include "uppercase/01-A.h"
#include "uppercase/02-B.h"
#include "uppercase/03-V.h"
#include "uppercase/04-G.h"
#include "uppercase/05-D.h"
#include "uppercase/06-YE.h"
#include "uppercase/07-YO.h"
#include "uppercase/08-J.h"
#include "uppercase/09-Z.h"
#include "uppercase/10-I.h"
#include "uppercase/11-IY.h"
#include "uppercase/12-K.h"
#include "uppercase/13-L.h"
#include "uppercase/14-M.h"
#include "uppercase/15-N.h"
#include "uppercase/16-O.h"
#include "uppercase/17-P.h"
#include "uppercase/18-R.h"
#include "uppercase/19-S.h"
#include "uppercase/20-T.h"
#include "uppercase/21-U.h"
#include "uppercase/22-F.h"
#include "uppercase/23-H.h"
#include "uppercase/24-C.h"
#include "uppercase/25-CH.h"
#include "uppercase/26-SH.h"
#include "uppercase/27-SCH.h"
#include "uppercase/28-ER.h"
#include "uppercase/29-ERI.h"
#include "uppercase/30-ERE.h"
#include "uppercase/31-E.h"
#include "uppercase/32-YU.h"
#include "uppercase/33-YA.h"

#endif